# Generated by Django 5.0.4 on 2024-04-30 13:40

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_delete_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities_Ly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=43)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('name_ar', models.CharField(max_length=85)),
                ('name_en', models.CharField(max_length=47)),
                ('region_no', models.IntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
