# Generated by Django 5.0.4 on 2024-04-30 14:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_cities_ly'),
    ]

    operations = [
        migrations.CreateModel(
            name='projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.FloatField()),
                ('project_id', models.FloatField()),
                ('project_no', models.FloatField()),
                ('project_na', models.CharField(max_length=254)),
                ('region', models.CharField(max_length=31)),
                ('city', models.CharField(max_length=75)),
                ('excutive', models.CharField(max_length=23)),
                ('field', models.CharField(max_length=36)),
                ('activity', models.CharField(max_length=80)),
                ('descriptio', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
