# Generated by Django 5.0.4 on 2024-05-08 21:37

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import map.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_regions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Municip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='type_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='appForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=130)),
                ('location', models.CharField(max_length=26)),
                ('regist_date', models.DateField()),
                ('description', models.TextField(max_length=200)),
                ('person', models.CharField(max_length=88)),
                ('possition', models.CharField(max_length=50)),
                ('nation', models.CharField(max_length=30)),
                ('passport', models.CharField(max_length=25)),
                ('phone1', models.CharField(max_length=16)),
                ('phone2', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=26)),
                ('email', models.EmailField(max_length=25)),
                ('image', models.ImageField(upload_to=map.models.image_upload)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_owner', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.area')),
                ('type_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.type_activity')),
            ],
        ),
    ]
