# Generated by Django 5.0.4 on 2024-05-08 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_area_municip_type_activity_appform'),
    ]

    operations = [
        migrations.AddField(
            model_name='appform',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.regions'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appform',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.municip'),
        ),
    ]
