# Generated by Django 5.0.4 on 2024-05-11 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_alter_appform_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='municip',
            name='region',
            field=models.CharField(max_length=43, null=True),
        ),
        migrations.AlterField(
            model_name='appform',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.municip', verbose_name='Enter The city'),
        ),
        migrations.AlterField(
            model_name='appform',
            name='region',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة'),
            preserve_default=False,
        ),
    ]
