# Generated by Django 5.0.4 on 2024-05-11 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_municip_region_alter_appform_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municip',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.regions'),
        ),
    ]
