# Generated by Django 5.0.4 on 2024-05-11 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_alter_municip_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cities_ly',
            old_name='region',
            new_name='region_name',
        ),
    ]
