# Generated by Django 5.0.4 on 2024-05-11 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_rename_region_cities_ly_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities_ly',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.regions'),
        ),
    ]
