# Generated by Django 5.0.4 on 2024-05-11 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_cities_ly_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='excutive',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='fid',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='region',
        ),
    ]
