# Generated by Django 5.0.4 on 2024-05-12 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_remove_projects_latitude_remove_projects_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.municip'),
        ),
    ]
