# Generated by Django 5.0.4 on 2024-05-14 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0018_alter_projects_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
