# Generated by Django 5.0.4 on 2024-05-15 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_projects_latitude_projects_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='regist_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
