# Generated by Django 5.0.4 on 2024-05-16 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_projects_regist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
