# Generated by Django 5.0.4 on 2024-05-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_projects_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=30)),
                ('passport', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=25)),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
