# Generated by Django 5.0.4 on 2024-05-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_applicants'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Applicants',
            new_name='Investors',
        ),
    ]
