# Generated by Django 5.0.4 on 2024-05-18 13:46

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_rename_appform_applicants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investors',
            old_name='passport',
            new_name='type_currency',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='area',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='description',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='image',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='location',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='region',
        ),
        migrations.RemoveField(
            model_name='applicants',
            name='type_activity',
        ),
        migrations.AddField(
            model_name='investors',
            name='invest_cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_no', models.FloatField()),
                ('proj_name', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=36)),
                ('regist_date', models.DateField(auto_now=True, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.area')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.municip')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة')),
                ('type_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.type_activity')),
            ],
        ),
        migrations.DeleteModel(
            name='projects',
        ),
    ]
