# Generated by Django 5.0.4 on 2024-05-18 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_rename_passport_investors_type_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_no', models.FloatField()),
                ('proj_name', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=75)),
                ('field', models.CharField(max_length=36)),
                ('regist_date', models.DateField(auto_now=True, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('active', models.BooleanField(default=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.area')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.municip')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة')),
                ('type_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.type_activity')),
            ],
        ),
    ]
