# Generated by Django 5.0.4 on 2024-05-18 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0026_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='city',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='field',
        ),
    ]
