# Generated by Django 5.0.4 on 2024-05-19 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_remove_locations_type_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.projects'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='investors',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.projects'),
            preserve_default=False,
        ),
    ]
