# Generated by Django 5.0.4 on 2024-05-19 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_applicants_project_investors_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.projects'),
            preserve_default=False,
        ),
    ]
