# Generated by Django 5.0.4 on 2024-05-19 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_locations_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='proj_id',
            field=models.FloatField(default=1, verbose_name=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة')),
            preserve_default=False,
        ),
    ]
