# Generated by Django 5.0.4 on 2024-05-19 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_projects_proj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='projects',
            name='regist_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
