# Generated by Django 5.0.4 on 2024-05-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_alter_projects_area_alter_projects_proj_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
