# Generated by Django 5.0.4 on 2024-05-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0033_alter_projects_proj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.CharField(default=0, max_length=25, null=True),
        ),
    ]
