# Generated by Django 5.0.4 on 2024-05-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0034_alter_projects_proj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investors',
            name='invest_cost',
            field=models.FloatField(),
        ),
    ]
