# Generated by Django 5.0.4 on 2024-05-20 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_alter_investors_invest_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='map.projects'),
        ),
        migrations.AlterField(
            model_name='investors',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investors', to='map.projects'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
