# Generated by Django 5.0.4 on 2024-05-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0036_alter_applicants_project_alter_investors_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.projects'),
        ),
        migrations.AlterField(
            model_name='locations',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة'),
        ),
    ]
