# Generated by Django 5.0.4 on 2024-05-22 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_alter_locations_project_alter_locations_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='area',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='location',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='project',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='region',
        ),
    ]
