# Generated by Django 5.0.4 on 2024-05-23 16:11

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_remove_locations_area_remove_locations_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
    ]
