# Generated by Django 5.0.4 on 2024-05-23 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_projects_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='active',
        ),
        migrations.AlterField(
            model_name='projects',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.area'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.CharField(default=0, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='regist_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='type_activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.type_activity'),
        ),
    ]
