# Generated by Django 5.0.4 on 2024-05-23 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_remove_projects_active_alter_projects_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='city',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='field',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
