# Generated by Django 5.0.4 on 2024-05-24 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0041_projects_city_projects_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='city',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='field',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='geom',
        ),
        migrations.AlterField(
            model_name='projects',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.municip'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة'),
            preserve_default=False,
        ),
    ]
