# Generated by Django 5.0.4 on 2024-05-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_remove_projects_city_remove_projects_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='city',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
