# Generated by Django 5.0.4 on 2024-05-24 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_projects_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='area',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='map.area'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='city',
            field=models.CharField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='proj_id',
            field=models.CharField(default=0, max_length=25),
        ),
    ]
