# Generated by Django 5.0.4 on 2024-05-24 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0044_alter_projects_area_alter_projects_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='map.projects'),
        ),
    ]
