# Generated by Django 5.0.4 on 2024-05-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0045_locations_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
