# Generated by Django 5.0.4 on 2024-05-25 13:00

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0046_alter_locations_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Houses',
            },
        ),
        migrations.AlterField(
            model_name='projects',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.area', verbose_name='ادخل المجال'),
        ),
    ]
