# Generated by Django 5.0.4 on 2024-05-25 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0047_house_alter_projects_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.regions', verbose_name='ادخل المنطقة'),
        ),
    ]
