# Generated by Django 5.0.4 on 2024-05-25 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0048_locations_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='map.area'),
        ),
    ]
