# Generated by Django 5.0.4 on 2024-04-20 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_banners_enquiry_gallery_galleryimage_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='pages.gallery'),
            preserve_default=False,
        ),
    ]
