# Generated by Django 5.0.4 on 2024-04-21 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_galleryimage_gallery'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallery',
            new_name='Gallerys',
        ),
    ]
