# Generated by Django 5.0.4 on 2024-04-21 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_gallery_gallerys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gallerys',
            new_name='gallery',
        ),
    ]
