# Generated by Django 5.0.4 on 2024-04-21 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_gallerys_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='img',
        ),
    ]
