# Generated by Django 5.0.4 on 2024-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_remove_gallery_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='img',
            field=models.ImageField(null=True, upload_to='services/'),
        ),
    ]
