# Generated by Django 5.0.4 on 2024-04-21 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_gallery_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='gallery',
        ),
        migrations.DeleteModel(
            name='gallery',
        ),
    ]
