# Generated by Django 5.0.4 on 2024-04-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_remove_galleryimage_gallery_delete_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='services/')),
            ],
        ),
    ]
