# Generated by Django 5.0.4 on 2024-04-21 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.gallery'),
        ),
    ]
