"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
#BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-739gtpy@v!qvk%(jh5pm+&u7tk79=i8rjsm01v2e))c$b668xh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
  #  'grappelli',
  #  'mainform.apps.SuitConfig',
    'products.apps.ProductsConfig',
    'map.apps.MapConfig',
    'django.contrib.gis',
    'pages.apps.PagesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
    'mapwidgets',
    'leaflet',
    #'geojosn',
    'job',
    'app',
    'mainform',
    'bootstrap4',
    'django_bootstrap5',
]
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'
# OR [os.path.join(BASE_DIR, 'templates')]
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'], #BASE_DIR / 'templates'
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
    #    'ENGINE': 'django.db.backends.sqlite3',
    #   'NAME': BASE_DIR / 'db.sqlite3',
    # django.db.backends.postgresql # django.contrib.gis.db.backends.postgis
    
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'lim',
        'USER': 'admin',
        'PASSWORD': 'Admin@PIB123',
        'HOST': '127.0.0.1',
        'PORT': '2453',
    }
}
#POSTGIS_VERSION = (2, 4, 3)


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

#CRISPY_TEMPLATE_PACK = 'bootstrap4'

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
    "/var/www/static/",
]

'''
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]
'''

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATE_INPUT_FORMATS = ('%d/%m/%Y','%d-%m-%Y','%d-%m-%Y')

#GDAL_LIBRARY_PATH = '/opt/homebrew/opt/gdal/lib/libgdal.dylib'
#GEOS_LIBRARY_PATH = '/opt/homebrew/opt/geos/lib/libgeos_c.dylib' 

PROJ_LIBRARY_PATH =r'C:\Program Files\QGIS 3.12\bin\o4w_env'
GDAL_LIBRARY_PATH =r'C:\Program Files\QGIS 3.12\bin\gdal204'
GEOS_LIBRARY_PATH =r'C:\Program Files\QGIS 3.12\bin\geos_c.dll'
PROJ_LIBRARY_PATH =r'C:\Program Files\QGIS 3.12\bin\proj'

os.environ['QGIS_PREFIX'] = 'C:/OSGeo4W64/apps/qgis'
#os.environ['GDAL_DATA'] = 'C:/OSGeo4W64/share/gdal'

STATICFILES_DIRS=(
    os.path.join(BASE_DIR, 'static'),
)

LEAFLET_CONFIG ={
    'DEFAULT_CENTER':(27.060677, 17.380922),#26.133567, 17.549336
    'DEFAULT_ZOOM' :6,
    'radius': 8,
    'MAX_ZOOM' : 20,
    'MIN_ZOOM' : 3,
    'RESET_VIEW': False,
    'NO_GLOBALS': False,
    'SCALE' : 'both',  # 'imperial'
    'ATTRIBUTION_PREFIX' : 'Insprired by Life in GIS'
}

MAP_WIDGETS = {
    "GooglePointFieldWidget": (
        ("zoom", 15),
        ("mapCenterLocationName", "tripoli"),
        ("GooglePlaceAutocompleteOptions", {'componentRestrictions': {'country': 'libya'}}),
        ("markerFitZoom", 12),
        ("scrollWheel", True),
        ("streetViewControl", True),
    ),
    "GOOGLE_MAP_API_KEY": "<AIzaSyDV_f1ECz8NFDVSzoqopavdi1A6u9hom60>" #'AIzaSyApdnBLqJeVW4c5t1Z32v88zVBVWyJnY1g'
}