# Generated by Django 5.0.4 on 2024-04-09 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0002_rename_name_mainform_project_name_mainform_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='email',
            field=models.EmailField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainform',
            name='phone',
            field=models.CharField(default='', max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainform',
            name='regist_date',
            field=models.DateField(auto_now=True),
        ),
    ]
