# Generated by Django 5.0.4 on 2024-04-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0003_mainform_email_mainform_phone_mainform_regist_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainform',
            name='regist_date',
            field=models.DateField(),
        ),
    ]
