# Generated by Django 5.0.4 on 2024-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0004_alter_mainform_regist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='person',
            field=models.CharField(default='', max_length=88),
            preserve_default=False,
        ),
    ]
