# Generated by Django 5.0.4 on 2024-04-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0006_rename_phone_mainform_phone1_mainform_nation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='type_activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
    ]
