# Generated by Django 5.0.4 on 2024-04-10 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0007_type_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='type_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainform.type_activity'),
            preserve_default=False,
        ),
    ]
