# Generated by Django 5.0.4 on 2024-04-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0008_mainform_type_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_activity',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
