# Generated by Django 5.0.4 on 2024-04-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0012_alter_mainform_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='address',
            field=models.CharField(default='', max_length=26),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainform',
            name='location',
            field=models.CharField(default='', max_length=26),
            preserve_default=False,
        ),
    ]
