# Generated by Django 5.0.4 on 2024-04-14 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0014_mainform_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_opportunnity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=50)),
                ('website', models.URLField()),
                ('passport_pic', models.FileField(upload_to='registred/')),
                ('notes', models.TextField(max_length=200)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_oppor', to='mainform.mainform')),
            ],
        ),
    ]
