# Generated by Django 5.0.4 on 2024-04-14 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0016_get_opportunnity_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mainform',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projcet_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
